### ISSUE TITLE
Colons in folder names on Windows is not allowed.  So when trying to clone this repo to a VS code running on windows it fails.

### ISSUE THREAD

**Issue by rudyolph** [jamesqquick/Build-A-Quiz-App-With-HTML-CSS-and-JavaScript#2]
Colons in folder names on Windows is not allowed.  So when trying to clone this repo to a VS code running on windows it fails.
...
Resolving deltas: 100% (75/75), done.
error: invalid path '4. Display Feedback for Correct:Incorrect Answers/app.css'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by moki929** [comment]
I have the same problems

**Comment by jamesqquick** [comment]
@rudyolph So sorry about that. I have removed the colon from the folder name.
