### ISSUE TITLE
highscores are random

### ISSUE THREAD

**Issue by denelan** [jamesqquick/Build-A-Quiz-App-With-HTML-CSS-and-JavaScript#3]
Up to the 12th one in end.js the score is a random math function and not the actual score.

const score = {
    score: Math.floor(Math.random() * 100),
    name: username.value

**Comment by rvidal** [comment]
Yes, that math function was added to allow James to show how the 5 score cut off works. If you substitute that math function with `mostRecentScore` then you should get the actual score.

**Comment by Ayesha1094** [comment]
Highscores are totally random. Its actual score is not working .Please help me out as I'm new to this coding world and Please fix it asap.

**Comment by jamesqquick** [comment]
@rvidal had the correct response. The scores were intended to be random for testing. The issue has been fixed so you can pull the latest code for the fix.

**Comment by Ayesha1094** [comment]
Thank you so much... I liked your videos ,it motivate me to do work in this field and I'm very thankful for your kind guidance and suggestions.

**Comment by jamesqquick** [comment]
@Ayesha1094 so glad to hear that :)
